services:
  orthanc:
    image: orthanc-plugin-python:latest
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    volumes:
      - ./libOrthancDicomWeb.so:/etc/orthanc/fracturedetect/libOrthancDicomWeb.so
      - ./libOrthancPython.so:/etc/orthanc/fracturedetect/libOrthancPython.so
    environment:
      - ORTHANC_NAME=HelloWorld
    command: [
      /run/secrets/    
    ]
secrets:
  orthanc.json:
    file: orthanc.json  
    
